import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('tracks', (t) => {
    t.increments('id')
    t.text('persistent_id').notNullable().unique()
    t.integer('track_id')
    t.text('name')
    t.text('artist')
    t.text('album_artist')
    t.text('album')
    t.text('composer')
    t.text('genre')
    t.text('grouping')
    t.text('work')
    t.text('movement_name')
    t.integer('movement_number')
    t.integer('movement_count')
    t.text('kind')
    t.text('track_type')
    t.text('location')
    t.integer('year')
    t.integer('track_number')
    t.integer('track_count')
    t.integer('disc_number')
    t.integer('disc_count')
    t.integer('total_time')
    t.integer('bit_rate')
    t.integer('sample_rate')
    t.integer('size')
    t.integer('play_count')
    t.integer('skip_count')
    t.integer('normalization')
    t.integer('artwork_count')
    t.integer('file_folder_count')
    t.integer('library_folder_count')
    t.integer('play_date')
    t.datetime('play_date_utc')
    t.datetime('skip_date')
    t.datetime('release_date')
    t.datetime('date_added')
    t.datetime('date_modified')
    t.text('sort_name')
    t.text('sort_artist')
    t.text('sort_album_artist')
    t.text('sort_album')
    t.text('sort_composer')
    t.boolean('loved')
    t.boolean('disliked')
    t.boolean('favorited')
    t.boolean('clean')
    t.boolean('explicit')
    t.boolean('compilation')
    t.boolean('purchased')
    t.boolean('apple_music')
    t.boolean('has_video')
    t.boolean('hd')
    t.boolean('music_video')
    t.boolean('playlist_only')
    t.boolean('part_of_gapless_album')
    t.text('content_hash')
    t.datetime('created_at').notNullable()
    t.datetime('updated_at').notNullable()
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable('tracks')
}
